name: looter
description: A simple yet fully-featured web scraper for both static and dynamically generated web pages.
version: 1.2.5
homepage: https://github.com/micazi/looter

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  collection: ^1.17.0
  html: ^0.15.1
  http: ^0.13.5
  puppeteer: ^2.17.0

dev_dependencies:
